# Qdrant Vector Database Kubernetes Deployment
# Persistent vector storage with clustering support

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: qdrant-neo4j-crawl4ai-mcp
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: qdrant-neo4j-crawl4ai-mcp
    app.kubernetes.io/version: "v1.7.4"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: qdrant-neo4j-crawl4ai-mcp-intelligence
    app.kubernetes.io/managed-by: kubernetes
spec:
  serviceName: qdrant-headless
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: qdrant
      app.kubernetes.io/instance: qdrant-neo4j-crawl4ai-mcp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qdrant
        app.kubernetes.io/instance: qdrant-neo4j-crawl4ai-mcp
        app.kubernetes.io/version: "v1.7.4"
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: qdrant-neo4j-crawl4ai-mcp-intelligence
        logging: promtail
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "6333"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.7.4
          imagePullPolicy: IfNotPresent
          
          ports:
            - name: http
              containerPort: 6333
              protocol: TCP
            - name: grpc
              containerPort: 6334
              protocol: TCP
            - name: p2p
              containerPort: 6335
              protocol: TCP
          
          env:
            - name: QDRANT__SERVICE__HTTP_PORT
              value: "6333"
            - name: QDRANT__SERVICE__GRPC_PORT
              value: "6334"
            - name: QDRANT__CLUSTER__ENABLED
              value: "true"
            - name: QDRANT__CLUSTER__P2P__PORT
              value: "6335"
            - name: QDRANT__STORAGE__STORAGE_PATH
              value: "/qdrant/storage"
            - name: QDRANT__LOG_LEVEL
              value: "INFO"
            - name: QDRANT__SERVICE__ENABLE_CORS
              value: "true"
            - name: QDRANT__SERVICE__MAX_REQUEST_SIZE_MB
              value: "32"
            - name: QDRANT__SERVICE__ENABLE_TLS
              value: "false"
            - name: QDRANT__STORAGE__WAL__WAL_CAPACITY_MB
              value: "32"
            - name: QDRANT__STORAGE__WAL__WAL_SEGMENTS_AHEAD
              value: "0"
            - name: QDRANT__STORAGE__PERFORMANCE__MAX_OPTIMIZATION_THREADS
              value: "2"
            - name: QDRANT__STORAGE__OPTIMIZERS__MEMMAP_THRESHOLD_KB
              value: "200000"
            - name: QDRANT__STORAGE__OPTIMIZERS__INDEXING_THRESHOLD_KB
              value: "10000"
          
          envFrom:
            - secretRef:
                name: qdrant-secrets
                optional: true
          
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2
              memory: 4Gi
          
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          
          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
            - name: qdrant-config
              mountPath: /qdrant/config
              readOnly: true
            - name: tmp
              mountPath: /tmp
      
      volumes:
        - name: qdrant-config
          configMap:
            name: qdrant-config
            defaultMode: 0644
        - name: tmp
          emptyDir:
            sizeLimit: 1Gi
      
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - qdrant
                topologyKey: kubernetes.io/hostname
      
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  
  volumeClaimTemplates:
    - metadata:
        name: qdrant-storage
        labels:
          app.kubernetes.io/name: qdrant
          app.kubernetes.io/instance: qdrant-neo4j-crawl4ai-mcp
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: fast-ssd
        resources:
          requests:
            storage: 50Gi
---
# Headless service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: qdrant-headless
  namespace: qdrant-neo4j-crawl4ai-mcp
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: qdrant-neo4j-crawl4ai-mcp
    app.kubernetes.io/component: headless-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: qdrant-neo4j-crawl4ai-mcp
  ports:
    - name: http
      port: 6333
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 6334
      targetPort: grpc
      protocol: TCP
    - name: p2p
      port: 6335
      targetPort: p2p
      protocol: TCP
---
# Regular service for external access
apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  namespace: qdrant-neo4j-crawl4ai-mcp
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: qdrant-neo4j-crawl4ai-mcp
    app.kubernetes.io/component: service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "6333"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: qdrant-neo4j-crawl4ai-mcp
  ports:
    - name: http
      port: 6333
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 6334
      targetPort: grpc
      protocol: TCP
  sessionAffinity: None
---
# ConfigMap for Qdrant configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: qdrant-config
  namespace: qdrant-neo4j-crawl4ai-mcp
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: qdrant-neo4j-crawl4ai-mcp
    app.kubernetes.io/component: config
data:
  config.yaml: |
    log_level: INFO
    
    service:
      host: 0.0.0.0
      http_port: 6333
      grpc_port: 6334
      enable_cors: true
      enable_tls: false
      max_request_size_mb: 32
      max_workers: 0
      
    cluster:
      enabled: true
      p2p:
        port: 6335
      consensus:
        tick_period_ms: 100
      
    storage:
      storage_path: ./storage
      snapshots_path: ./snapshots
      temp_path: ./temp
      
      wal:
        wal_capacity_mb: 32
        wal_segments_ahead: 0
        
      performance:
        max_search_threads: 0
        max_optimization_threads: 2
        
      optimizers:
        deleted_threshold: 0.2
        vacuum_min_vector_number: 1000
        default_segment_number: 0
        max_segment_size_kb: 5000000
        memmap_threshold_kb: 200000
        indexing_threshold_kb: 10000
        flush_interval_sec: 5
        max_optimization_threads: 2
        
      hnsw_index:
        m: 16
        ef_construct: 100
        full_scan_threshold: 10000
        max_indexing_threads: 0
        on_disk: false
        payload_m: 16
        
    telemetry:
      disabled: false